# Generated by Django 4.1.1 on 2022-10-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_qrcode_test", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testpage",
            name="qr_code_svg",
            field=models.TextField(blank=True, null=True, verbose_name="QR Code SVG"),
        ),
        migrations.AlterField(
            model_name="testpage",
            name="qr_code_usage",
            field=models.IntegerField(default=0, verbose_name="QR Code Usage Count"),
        ),
    ]
